"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { store } from "@/store/store";
import { Provider } from "react-redux";
import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import Sidebar from "@/components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (!isMounted) {
    return null;
  }

  const isAuthPage = pathname === "/login" || pathname === "/signup";

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex h-full">
          {!isAuthPage && <Sidebar />}
          <Provider store={store}>
            <main
              style={{
                flexGrow: 1,
                background: isAuthPage ? "none" : "#F3F3F7",
                padding: "3rem",
              }}
            >
              {!isAuthPage && <Navbar />}
              {children}
            </main>
          </Provider>
        </div>
      </body>
    </html>
  );
}
